---
- name: Make sure parted is installed
  become: yes
  package:
      name: parted
      state: present
  when: bd_install

- name: Create partition table
  become: yes
  command: "parted --script {{bd_block_device}} mklabel gpt"
  when: bd_install

- name: Create partition
  become: yes
  command: "parted --script {{bd_block_device}} mkpart primary {{bd_file_system}} 0% 100%"
  when: bd_install

- name: Create file system
  become: yes
  command: "mkfs.{{bd_file_system}} -f -L {{bd_label}} {{bd_block_device}}1"
  when: bd_install

- name: Create mount point
  become: yes
  file:
      path: "{{bd_mount_point}}"
      state: directory
  when: bd_install

- name: Mount the new partition
  become: yes
  mount:
      name: "{{bd_mount_point}}"
      src: "LABEL={{bd_label}}"
      fstype: "{{bd_file_system}}"
      opts: "{{bd_options}}"
      state: mounted
  when: bd_install

- name: Determine If We Are Running In AWS
  become: no
  set_fact:
      running_in_aws: ansible_user_id == "ec2-user"

- name: Configure Read Ahead Block Size
  become: yes
  cron:
      name: read-ahead
      special_time: reboot
      state: present
      user: root
      job: '/sbin/blockdev --setra 32 {{bd_block_device}}'
  when: mongodb_install and running_in_aws
