---
- name: Make sure parted is installed
  become: yes
  package: 
      name: parted
      state: present
  when: bd_install

- name: Create partition table
  become: yes
  command: "parted {{bd_block_device}} mklabel gpt"
  when: bd_install

- name: Create partition
  become: yes
  command: "parted {{bd_block_device}} mkpart primary {{bd_file_system}} 0% 100%"
  when: bd_install

- name: Create file system
  become: yes
  command: "mkfs.{{bd_file_system}} -L {{bd_label}} {{bd_block_device}}1"
  when: bd_install

- name: Create mount point
  become: yes
  file:
      path: "{{bd_mount_point}}"
      state: directory
  when: bd_install

- name: Mount the new partition
  become: yes
  mount:
      name: "{{bd_mount_point}}"
      src: "LABEL={{bd_label}}"
      fstype: "{{bd_file_system}}"
      state: present
  when: bd_install
