---
- name: Create partition table
  command: "parted {{bd_block_device}} mklabel gpt"
  become: yes
  when: bd_install

- name: Create partition
  command: "parted {{bd_block_device}} mkpart primary {{bd_file_system}} 0% 100%""
  become: yes
  when: bd_install
