---
- name: Create file system
  become: yes
  command: "mkfs.{{bd_file_system}} -f -L {{bd_label}} {{bd_block_device}}"
  when: bd_install and bd_create_partition

- name: Create mount point
  become: yes
  file:
      path: "{{bd_mount_point}}"
      state: directory
  when: bd_install

- name: Mount the device
  become: yes
  mount:
      name: "{{bd_mount_point}}"
      src: "LABEL={{bd_label}}"
      fstype: "{{bd_file_system}}"
      opts: "{{bd_options}}"
      state: mounted
  when: bd_install

# need a better way to determine this.  Hit the meta-data endpoint?
- name: Determine If We Are Running In AWS
  become: no
  set_fact:
      running_in_aws: ansible_user_id == "ec2-user"

- name: Configure Read Ahead Block Size
  become: yes
  cron:
      name: read-ahead
      special_time: reboot
      state: present
      user: root
      job: '/sbin/blockdev --setra 32 {{bd_block_device}}'
  when: bd_install and running_in_aws
